[project]
name = "context-centre-agents-unified-memory"
version = "0.1.0"
description = "MCP tools for lead data retrieval from Google Cloud Storage."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=3.3.1",
    "mcp[cli]>=1.27.1",
    "google-cloud-storage>=2.10.0",
    "uv"
]

[tool.setuptools]
py-modules = ["mcp_server", "gcs_modules"]

[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"
